// Mocks generated by Mockito 5.0.17 from annotations
// in applore_assignment_app/test/modal/service/product.service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:applore_assignment_app/modal/repository/product.repo.dart'
    as _i2;
import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  set baseDio(_i3.Dio? _baseDio) =>
      super.noSuchMethod(Invocation.setter(#baseDio, _baseDio),
          returnValueForMissingStub: null);

  _i4.Future<dynamic> getResponse() =>
      (super.noSuchMethod(Invocation.method(#getResponse, []),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);

  _i4.Future<String> statusResponse(_i3.Response<dynamic>? response) =>
      (super.noSuchMethod(Invocation.method(#statusResponse, [response]),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
}
