// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYzzt_RLU59iGAb9VxabMwjn2I23qs1uM',
    appId: '1:322768923860:android:2096fda2d62c52e60c9f41',
    messagingSenderId: '322768923860',
    projectId: 'fl-bloc-v8',
    storageBucket: 'fl-bloc-v8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxoV0584yrPtDKFGllJny_kjfiDz615k',
    appId: '1:322768923860:ios:33d8cf6f2f3bbe710c9f41',
    messagingSenderId: '322768923860',
    projectId: 'fl-bloc-v8',
    storageBucket: 'fl-bloc-v8.appspot.com',
    iosClientId: '322768923860-sh71100qibu7dt827hraimapugsf2cpm.apps.googleusercontent.com',
    iosBundleId: 'com.applore.assignment',
  );
}
