// Mocks generated by Mockito 5.0.17 from annotations
// in applore_assignment_app/test/modal/service/auth/auth.service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:applore_assignment_app/modal/service/auth/auth.service.dart'
    as _i3;
import 'package:applore_assignment_app/view/add_post/user.modal.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserModal].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserModal extends _i1.Mock implements _i2.UserModal {
  MockUserModal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set profile(_i4.User? _profile) =>
      super.noSuchMethod(Invocation.setter(#profile, _profile),
          returnValueForMissingStub: null);
  @override
  _i5.Stream<_i4.User?> checkAuthStatus() =>
      (super.noSuchMethod(Invocation.method(#checkAuthStatus, []),
          returnValue: Stream<_i4.User?>.empty()) as _i5.Stream<_i4.User?>);
}
